[package]
name = "rezis"
version = "0.1.0"
edition.workspace = true
license.workspace = true
description = "NestJS-inspired Rust backend framework for clean, modular APIs."

[dependencies]
axum = "0.8"
http = "1"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
thiserror = "2"
validator = { version = "0.20", features = ["derive"] }
tokio = { version = "1", features = ["macros", "net", "rt-multi-thread"] }
tower-http = { version = "0.6", features = ["trace", "cors"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["fmt", "env-filter"] }

[dev-dependencies]
tower = { version = "0.5", features = ["util"] }
